name: Demo Build
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: install && sleep 10
      - name: Run unit tests
        run: test:unit && sleep 30
      - name: Run integration tests
        run: test:integration && sleep 25
      - name: Run e2e tests
        run: test:e2e && sleep 25
      - name: Build project
        run: build && sleep 25
      - name: Deploy to production
        run: deploy && sleep 25
      - name: Send notifications
        run: notify && sleep 25
