name: Demo Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test:unit
      - name: Run integration tests
        run: pnpm test:integration
      - name: Run e2e tests
        run: pnpm test:e2e
      - name: Build project
        run: pnpm build
      - name: Deploy to production
        run: pnpm deploy
      - name: Send notifications
        run: pnpm notify
